- name: Get secgroup_id
  include: lookup.yml
  with_items:
    - "{{ secgroups }}"
  loop_control:
    loop_var: secgroup_name

- name: Send request to API (create security group)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  when:
    - secgroups is defined
    - secgroup_name not in secgroup_names
  register: secgroupcreate
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgroupcreate.status == 200
  changed_when: false
  with_items:
    - "{{ secgroups }}"
  loop_control:
    loop_var: secgroup_name

- name: Create securiy group rules
  include: rule_create.yml
  when:
    - secgroups is defined
    - secgroup_name not in secgroup_names
  with_items:
    - "{{ secgroups }}"
  loop_control:
    loop_var: secgroup_name
