- name: Send request to API (list security groups for search vpc_id)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups?vpc_id={{ vpc_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgrouplistvpc
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgrouplistvpc.status == 200
  changed_when: false
  when: vpc_id is defined

- name: Send request to API (list security groups)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgrouplist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgrouplist.status == 200
  changed_when: false
  when: vpc_id is not defined

- debug:
    msg: "{{ secgrouplistvpc.json }}"
  when: vpc_id is defined

- debug:
    msg: "{{ secgrouplist.json }}"
  when: vpc_id is not defined
