- name: Send request to API (list security groups)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgroup_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgroup_result.status == 200
  changed_when: false
  when:
    - secgroup_name is defined

- name: Set fact for secgroup_id if secgroup_name is defined
  set_fact:
    secgroup_id: "{{ (secgroup_result.content|from_json)|json_query(\"security_groups[?name=='\" + secgroup_name + \"'].id|[0]\") }}"
  when:
    - secgroup_name is defined and secgroup_name| length != 0

- name: Set empty fact secgroup_names
  set_fact:
    secgroup_names: []
  when:
    - secgroup_names is not defined

- name: Set empty fact secgroup_ids
  set_fact:
    secgroup_ids: []
  when:
    - secgroup_ids is not defined

- name: Set fact for secgroup_ids if secgroup_id is defined
  set_fact:
    secgroup_ids: "{{ secgroup_ids }} + [ '{{ secgroup_id }}' ]"
    secgroup_names: "{{ secgroup_names }} + [ '{{ secgroup_name }}' ]"
  when:
    - secgroup_id is defined and secgroup_id| length != 0
