- name: Send request to API (security group list)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgroup_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgroup_result.status == 200
  changed_when: false
  when:
    - secgroup_name is defined

- name: Set fact for secgroup_id if secgroup_name is defined
  set_fact:
    secgroup_id: "{{ (secgroup_result.content|from_json)|json_query(\"security_groups[?name=='\" + secgroup_name + \"'].id|[0]\") }}"
  when:
    - secgroup_name is defined and secgroup_name| length != 0

- name: Send request to API (securiy group rule list)
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/security-group-rules?security_group_id={{ secgroup_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgrouprule_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgrouprule_result.status == 200
  changed_when: false
  when:
    - secgroup_id is defined

- name: Send request to API (remove security group default rules)
  vars:
    secgrouprule_id: "{{ item }}"
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/security-group-rules/{{ secgrouprule_id }}"
    method: DELETE
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    status_code: 200,201,202,203,204
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgroup_rule
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgroup_rule.status == 200 or secgroup_rule.status == 201 or secgroup_rule.status == 202 or secgroup_rule.status == 203 or secgroup_rule.status == 204
  changed_when: false
  when:
    - secgrouprule_result is defined
  with_items:
    - "{{ secgrouprule_result.json|json_query('security_group_rules[].id') }}"

- name: Send request to API (create security group rule)
  vars:
    secgrouprule_part: "{{ item.split(';') }}"
  uri:
    url: "{{ AUTH_URL_VPC }}/v2.0/security-group-rules"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    status_code: 200,201,202,203,204,409
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'rule_create.json.j2')|to_json }}"
  register: secgrouprule
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgrouprule.status == 200 or secgrouprule.status == 201 or secgrouprule.status == 202 or secgrouprule.status == 203 or secgrouprule.status == 204 or secgrouprule.status == 409
  changed_when: false

  when:
    - secgroup_id is defined
    - secgrouprules is defined
  with_items:
    - "{{ secgrouprules }}"
