- name: Lookup secgroup_id
  include: lookup.yml

- name: Send request to API (show security group)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/security-groups/{{ secgroup_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgroupdetail
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: secgroupdetail.status == 200
  changed_when: false
  when:
    - secgroup_id is defined

- debug:
    msg: "{{ secgroupdetail.json }}"
  when:
    - secgroup_id is defined
